### ISSUE TITLE
Style consistency for Javascript

### ISSUE THREAD

**Issue by polortiz4** [epvienneau/skin_lesion_classification_app#50]
Do we need to follow any language convention for javascript? Also, is there the equivalent of a pytest --pep for it?

**Comment by mlp6** [comment]
It is always good practice to impose a style convention for a project.  While I personally like PEP8 for Python (since it is the most ubiquitous), I think that the Google style guide for JavaScript is pretty good (https://google.github.io/styleguide/jsguide.html).  Regardless of which specific style convention you choose, consistency is the most important thing.

Your equivalent for `pytest --pep8` is to have a JS linting tool run on your code.  If you are using something like JetBrains Webstorm to code your JavaScript, it will use tools like `jslint` (https://www.jetbrains.com/help/webstorm/jslint.html).  You can choose your favorite.
